### PR TITLE
Cache Atm. Calculations to Improve Runtime

### PR DESCRIPTION
**Pull request by djperrefort**
This PR is intended to address Issue #47 by implementing memoization for the `snat_sim.models.FixedResTransmission.__call__` and `snat_sim.models.PWVModel.pwv_los` functions.

I've included a profiling script `scripts/profiling/profile_fitting.py` which runs 100 light-curves through the pipeline. Profiling results for the script have also been included in the same directory.

Since these two functions accept NumPy arguments, I've needed to add a custom wrapper to handle the argument caching. The code is available in `snat_sim.cache_tools` but I will paste it here for reference:

```
def array_to_tuple(np_array):

    try:
        return tuple(array_to_tuple(_) for _ in np_array)

    except TypeError:
        return np_array


def np_cache(*args, **kwargs):
    """LRU cache implementation for functions whose FIRST parameter is a numpy array"""

    def decorator(function):
        @wraps(function)
        def wrapper(*args, **kwargs):
            return cached_wrapper(*array_to_tuple(args), **kwargs)

        @lru_cache(*args, **kwargs)
        def cached_wrapper(*args, **kwargs):
            return function(*args, **kwargs)

        # copy lru_cache attributes over too
        wrapper.cache_info = cached_wrapper.cache_info
        wrapper.cache_clear = cached_wrapper.cache_clear

        return wrapper

    return decorator
```

The basic idea is to cast all arguments as hashable tuples using `array_to_tuple`. Unfortunately, the recursive calls end up taking 28% of the total runtime in the profiling script. I would like to find an alternative approach or implementation with less overhead.

### CODE REVIEW

**Comment by djperrefort** [comment]
@wmwv I've pushed a few changes to master. If you haven't done so already, you may wish to update this branch.

**Comment by djperrefort** [comment]
@wmwv  I've pushed some updates on this that promise to reduce the cache overhead. Lets add this to the agenda for our meeting this Monday.

**Comment by wmwv** [comment]
When I run `scripts/profiling/profile_fitting.py` from version `8c050d3`, I get 
```
[Serenity SN-PWV] python scripts/profiling/profile_fitting.py
Traceback (most recent call last):
  File "scripts/profiling/profile_fitting.py", line 12, in <module>
    sn_model_sim = create_sn_model('salt2-extended', create_pwv_model(4, cache_pwv_los=False), cache_trans=False)
TypeError: create_pwv_model() got an unexpected keyword argument 'cache_pwv_los'
```

**Comment by wmwv** [comment]
Should I be using a different version?  `8c050d3` is listed as the tip of `origing/djperrefort/profiling` as of right now (2020-11-30 09:07 EST).

**Comment by wmwv** [comment]
The `create_pwv_model` function defined in `scripts/fitting_cli.py` is the only one I see in the repository:

```
[Serenity SN-PWV] grep -R create_pwv_model *
Binary file scripts/__pycache__/fitting_cli.cpython-38.pyc matches
scripts/profiling/profile_fitting.py:from scripts.fitting_cli import create_pwv_model, create_sn_model
scripts/profiling/profile_fitting.py:    sn_model_sim = create_sn_model('salt2-extended', create_pwv_model(4, cache_pwv_los=False), cache_trans=False)
scripts/profiling/profile_fitting.py:    sn_model_fit = create_sn_model('salt2-extended', create_pwv_model(4, cache_pwv_los=250_000), cache_trans=250_000)
Binary file scripts/profiling/profile_fitting.pstat matches
Binary file scripts/profiling/old_profile_fitting.pstat matches
scripts/fitting_cli.py:def create_pwv_model(pwv_variability):
scripts/fitting_cli.py:    pwv_model_sim = create_pwv_model(cli_args.sim_variability)
scripts/fitting_cli.py:    pwv_model_fit = create_pwv_model(cli_args.fit_variability)
```

**Comment by djperrefort** [comment]
@mwv It looks like a missed function call when refactoring. I've pushed a fix.

**Comment by djperrefort** [comment]
@wmwv I've put some more thought into pre-tabulating the airmass values as you suggested. I was hesitant to add a pre-processing step to the pipeline, mostly because of the added overhead. Instead, I pushed what I think is a good middle ground between using pre-tabulated and on-the-fly calculated airmasses.

Instead of tabulating the airmass values on disk ahead of time, I propose calculating them as necessary and then caching them to disk as we go. Successive pipeline runs can then take advantage of cached values from previous runs (assuming the same cadence is used, but with no dependence on the assumed atmospheric model). The `joblib` package allows us to do this with only a few lines of code so the implementation is easy.

I've pushed updated profiling results (in pstat and png format) for you're review. You will find results without caching the airmass, with caching turned on but with no pre-tabulated values, and with caching turned on using pre-tabulated airmasses. Overall the runtime for **fitting** 100 light-curves drops from 45 seconds to 31 seconds.

**Pull request merged**
